<?xml version="1.0" encoding="UTF-8"?><testrun name="IntervalGeneticSolverTest" project="GOptimum" tests="8" started="6" failures="5" errors="0" ignored="0">
  <testsuite name="solvers.IntervalGeneticSolverTest" incomplete="true">
    <testcase name="test1" classname="solvers.IntervalGeneticSolverTest" time="0.0">
      <failure>java.lang.AssertionError: Wrong optimum VALUE was found by IntervalGeneticSolver for x0^2 function!&#13;
	at org.junit.Assert.fail(Assert.java:93)&#13;
	at testharness.TestHarness.solveFunction(TestHarness.java:113)&#13;
	at testharness.TestHarness.f_DeJong_Zero(TestHarness.java:30)&#13;
	at solvers.IntervalGeneticSolverTest.test1(IntervalGeneticSolverTest.java:25)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)&#13;
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)&#13;
	at java.lang.reflect.Method.invoke(Unknown Source)&#13;
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:45)&#13;
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)&#13;
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:42)&#13;
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)&#13;
	at org.junit.internal.runners.statements.FailOnTimeout$StatementThread.run(FailOnTimeout.java:62)&#13;
&#13;
</failure>
    </testcase>
    <testcase name="test1p" classname="solvers.IntervalGeneticSolverTest" time="0.0">
      <failure>java.lang.AssertionError: Wrong optimum VALUE was found by IntervalGeneticSolver for x0^2+x1^2 function!&#13;
	at org.junit.Assert.fail(Assert.java:93)&#13;
	at testharness.TestHarness.solveFunction(TestHarness.java:113)&#13;
	at testharness.TestHarness.f_DeJong_Zero(TestHarness.java:30)&#13;
	at solvers.IntervalGeneticSolverTest.test1p(IntervalGeneticSolverTest.java:33)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)&#13;
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)&#13;
	at java.lang.reflect.Method.invoke(Unknown Source)&#13;
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:45)&#13;
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)&#13;
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:42)&#13;
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)&#13;
	at org.junit.internal.runners.statements.FailOnTimeout$StatementThread.run(FailOnTimeout.java:62)&#13;
&#13;
</failure>
    </testcase>
    <testcase name="test11" classname="solvers.IntervalGeneticSolverTest" time="0.0">
      <failure>java.lang.AssertionError: Wrong optimum VALUE was found by IntervalGeneticSolver for x0^2+x1^2+x2^2 function!&#13;
	at org.junit.Assert.fail(Assert.java:93)&#13;
	at testharness.TestHarness.solveFunction(TestHarness.java:113)&#13;
	at testharness.TestHarness.f_DeJong_NotSim(TestHarness.java:37)&#13;
	at solvers.IntervalGeneticSolverTest.test11(IntervalGeneticSolverTest.java:39)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)&#13;
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)&#13;
	at java.lang.reflect.Method.invoke(Unknown Source)&#13;
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:45)&#13;
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)&#13;
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:42)&#13;
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)&#13;
	at org.junit.internal.runners.statements.FailOnTimeout$StatementThread.run(FailOnTimeout.java:62)&#13;
&#13;
</failure>
    </testcase>
    <testcase name="test2" classname="solvers.IntervalGeneticSolverTest" time="0.038">
      <failure>java.lang.AssertionError: Wrong optimum VALUE was found by IntervalGeneticSolver for (2*x^3*y-y^3)^2+(6*x+y-y^2)^2 function!&#13;
	at org.junit.Assert.fail(Assert.java:93)&#13;
	at testharness.TestHarness.solveFunction(TestHarness.java:113)&#13;
	at testharness.TestHarness.f_Price5_Zero(TestHarness.java:47)&#13;
	at solvers.IntervalGeneticSolverTest.test2(IntervalGeneticSolverTest.java:45)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)&#13;
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)&#13;
	at java.lang.reflect.Method.invoke(Unknown Source)&#13;
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:45)&#13;
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)&#13;
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:42)&#13;
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)&#13;
	at org.junit.internal.runners.statements.FailOnTimeout$StatementThread.run(FailOnTimeout.java:62)&#13;
&#13;
</failure>
    </testcase>
    <testcase name="test3" classname="solvers.IntervalGeneticSolverTest" time="0.049">
      <failure>java.lang.AssertionError: Wrong optimum VALUE was found by IntervalGeneticSolver for x^2-(cos(18*x)+cos(18*y))+y^2 function!&#13;
	at org.junit.Assert.fail(Assert.java:93)&#13;
	at testharness.TestHarness.solveFunction(TestHarness.java:113)&#13;
	at testharness.TestHarness.f_Rastrigin10(TestHarness.java:58)&#13;
	at solvers.IntervalGeneticSolverTest.test3(IntervalGeneticSolverTest.java:51)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)&#13;
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)&#13;
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)&#13;
	at java.lang.reflect.Method.invoke(Unknown Source)&#13;
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:45)&#13;
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)&#13;
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:42)&#13;
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)&#13;
	at org.junit.internal.runners.statements.FailOnTimeout$StatementThread.run(FailOnTimeout.java:62)&#13;
&#13;
</failure>
    </testcase>
    <testcase name="test4" classname="solvers.IntervalGeneticSolverTest" incomplete="true"/>
    <testcase name="test5" classname="solvers.IntervalGeneticSolverTest" incomplete="true"/>
    <testcase name="test5_1" classname="solvers.IntervalGeneticSolverTest" incomplete="true"/>
  </testsuite>
</testrun>
